name = "drksci-landing"
pages_build_output_dir = "build"
compatibility_date = "2024-01-01"

[env.production.vars]
DEPLOY_URL = "https://drksci.pages.dev"
GITHUB_REPO = "https://github.com/roland-id-au/drksci-landing"